---
- name: Include tasks from validate_docker_execute.yml
  ansible.builtin.include_tasks: validate_docker_execute.yml

- name: Include tasks from cleanup_containers.yml
  ansible.builtin.include_tasks: cleanup_containers.yml

- name: Include tasks from cleanup_images.yml
  ansible.builtin.include_tasks: cleanup_images.yml

# contrail_additions: Cleanup Contrail Images
- include_tasks: cleanup_contrail.yml

- name: Include tasks from cleanup_host.yml
  ansible.builtin.include_tasks: cleanup_host.yml

